all:
  children:
    web-servers:
      hosts:
#        web1:
#        web2:
        web5:
          ansible_user: ubuntu
    localhost:
      local1:
        ansible_connection: local
    linux:
      children:
        web-servers:
