all:
  children:
    web-servers:
      hosts:
#        web1:
#        web2:
        web4:
    docker:
      children:
        web-servers
    localhost:
      local1:
        ansible_connection: local
